[options]
addons_path = /mnt/extra-addons/enterprise-c19.0,/mnt/extra-addons
admin_passwd =dildil2odoo$$  
db_host = db
db_user = odoo
db_port = 5432
#proxy_mode = True
#xmlrpc_interface = 127.0.0.1
#netrpc_interface = 127.0.0.1

